[versions]
koin = "3.5.3"
navigation = "2.7.6"
kotlin = "1.9.0"

[libraries]
koin-core = {module = "io.insert-koin:koin-core", version.ref = "koin"}
koin-android = {module = "io.insert-koin:koin-android", version.ref = "koin"}
navigation-fragment = {module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation"}
navigation-ui = {module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation"}
[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
